/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTeamRouteImport } from './routes/_layout.team'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout.products.index'
import { Route as LayoutInquiriesIndexRouteImport } from './routes/_layout.inquiries.index'
import { Route as LayoutAllPostsIndexRouteImport } from './routes/_layout.all-posts.index'
import { Route as LayoutProductsCreateNewProductRouteImport } from './routes/_layout.products.create-new-product'
import { Route as LayoutInquiriesInquiryIdRouteImport } from './routes/_layout.inquiries.$inquiryId'
import { Route as LayoutAllPostsCreateNewPostRouteImport } from './routes/_layout.all-posts.create-new-post'
import { Route as LayoutAllPostsPostIdRouteImport } from './routes/_layout.all-posts.$postId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInquiriesIndexRoute = LayoutInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAllPostsIndexRoute = LayoutAllPostsIndexRouteImport.update({
  id: '/all-posts/',
  path: '/all-posts/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsCreateNewProductRoute =
  LayoutProductsCreateNewProductRouteImport.update({
    id: '/products/create-new-product',
    path: '/products/create-new-product',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInquiriesInquiryIdRoute =
  LayoutInquiriesInquiryIdRouteImport.update({
    id: '/inquiries/$inquiryId',
    path: '/inquiries/$inquiryId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAllPostsCreateNewPostRoute =
  LayoutAllPostsCreateNewPostRouteImport.update({
    id: '/all-posts/create-new-post',
    path: '/all-posts/create-new-post',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAllPostsPostIdRoute = LayoutAllPostsPostIdRouteImport.update({
  id: '/all-posts/$postId',
  path: '/all-posts/$postId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/all-posts/$postId': typeof LayoutAllPostsPostIdRoute
  '/all-posts/create-new-post': typeof LayoutAllPostsCreateNewPostRoute
  '/inquiries/$inquiryId': typeof LayoutInquiriesInquiryIdRoute
  '/products/create-new-product': typeof LayoutProductsCreateNewProductRoute
  '/all-posts/': typeof LayoutAllPostsIndexRoute
  '/inquiries/': typeof LayoutInquiriesIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/': typeof LayoutIndexRoute
  '/all-posts/$postId': typeof LayoutAllPostsPostIdRoute
  '/all-posts/create-new-post': typeof LayoutAllPostsCreateNewPostRoute
  '/inquiries/$inquiryId': typeof LayoutInquiriesInquiryIdRoute
  '/products/create-new-product': typeof LayoutProductsCreateNewProductRoute
  '/all-posts': typeof LayoutAllPostsIndexRoute
  '/inquiries': typeof LayoutInquiriesIndexRoute
  '/products': typeof LayoutProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/all-posts/$postId': typeof LayoutAllPostsPostIdRoute
  '/_layout/all-posts/create-new-post': typeof LayoutAllPostsCreateNewPostRoute
  '/_layout/inquiries/$inquiryId': typeof LayoutInquiriesInquiryIdRoute
  '/_layout/products/create-new-product': typeof LayoutProductsCreateNewProductRoute
  '/_layout/all-posts/': typeof LayoutAllPostsIndexRoute
  '/_layout/inquiries/': typeof LayoutInquiriesIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/team'
    | '/all-posts/$postId'
    | '/all-posts/create-new-post'
    | '/inquiries/$inquiryId'
    | '/products/create-new-product'
    | '/all-posts/'
    | '/inquiries/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/team'
    | '/'
    | '/all-posts/$postId'
    | '/all-posts/create-new-post'
    | '/inquiries/$inquiryId'
    | '/products/create-new-product'
    | '/all-posts'
    | '/inquiries'
    | '/products'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/settings'
    | '/_layout/team'
    | '/_layout/'
    | '/_layout/all-posts/$postId'
    | '/_layout/all-posts/create-new-post'
    | '/_layout/inquiries/$inquiryId'
    | '/_layout/products/create-new-product'
    | '/_layout/all-posts/'
    | '/_layout/inquiries/'
    | '/_layout/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inquiries/': {
      id: '/_layout/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof LayoutInquiriesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/all-posts/': {
      id: '/_layout/all-posts/'
      path: '/all-posts'
      fullPath: '/all-posts/'
      preLoaderRoute: typeof LayoutAllPostsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/create-new-product': {
      id: '/_layout/products/create-new-product'
      path: '/products/create-new-product'
      fullPath: '/products/create-new-product'
      preLoaderRoute: typeof LayoutProductsCreateNewProductRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inquiries/$inquiryId': {
      id: '/_layout/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/inquiries/$inquiryId'
      preLoaderRoute: typeof LayoutInquiriesInquiryIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/all-posts/create-new-post': {
      id: '/_layout/all-posts/create-new-post'
      path: '/all-posts/create-new-post'
      fullPath: '/all-posts/create-new-post'
      preLoaderRoute: typeof LayoutAllPostsCreateNewPostRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/all-posts/$postId': {
      id: '/_layout/all-posts/$postId'
      path: '/all-posts/$postId'
      fullPath: '/all-posts/$postId'
      preLoaderRoute: typeof LayoutAllPostsPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAllPostsPostIdRoute: typeof LayoutAllPostsPostIdRoute
  LayoutAllPostsCreateNewPostRoute: typeof LayoutAllPostsCreateNewPostRoute
  LayoutInquiriesInquiryIdRoute: typeof LayoutInquiriesInquiryIdRoute
  LayoutProductsCreateNewProductRoute: typeof LayoutProductsCreateNewProductRoute
  LayoutAllPostsIndexRoute: typeof LayoutAllPostsIndexRoute
  LayoutInquiriesIndexRoute: typeof LayoutInquiriesIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAllPostsPostIdRoute: LayoutAllPostsPostIdRoute,
  LayoutAllPostsCreateNewPostRoute: LayoutAllPostsCreateNewPostRoute,
  LayoutInquiriesInquiryIdRoute: LayoutInquiriesInquiryIdRoute,
  LayoutProductsCreateNewProductRoute: LayoutProductsCreateNewProductRoute,
  LayoutAllPostsIndexRoute: LayoutAllPostsIndexRoute,
  LayoutInquiriesIndexRoute: LayoutInquiriesIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
